name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build the stack
      run: docker-compose up -d
    - name: Run tests
      run: sbt test 
      env:
        AWS_ACCESS_KEY_ID: xxx
        AWS_SECRET_ACCESS_KEY: xxx
        AWS_DEFAULT_REGION: us-east-1
